repos:
  # Rust系ツール（ローカルで定義）
  - repo: local
    hooks:
      - id: cargo-fmt
        name: cargo fmt
        entry: cargo
        args: ["fmt", "--", "--check"]
        language: system
        types: [rust]

      - id: cargo-clippy
        name: cargo clippy
        entry: cargo
        args: ["clippy", "--all-features", "--bins","--", "-D", "warnings"]
        language: system
        types: [rust]
        pass_filenames: false

      - id: cargo-check
        name: cargo check
        entry: cargo
        args: ["check"]
        language: system
        types: [rust]
        pass_filenames: false

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-added-large-files
      - id: check-yaml
      - id: check-merge-conflict
