[build]
#target = "x86_64-rust-mikan-os-elf.json"
target = "x86_64-unknown-uefi"

[unstable]
build-std = ["core"]

#[target.'x86_64-rust-mikan-os-elf.json']
#linker = "lld-link"
#rustflags = [
#  "-C", "link-arg=/ENTRY:kernel_main",
#  "-C", "link-arg=/SUBSYSTEM:EFI_APPLICATION"
#]
